# Generated by Django 2.1.8 on 2019-07-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreshApp', '0002_goods_goods_under'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='商品类型名称')),
                ('description', models.TextField(max_length=32, verbose_name='商品类型描述')),
                ('picture', models.ImageField(upload_to='buyer/images')),
            ],
        ),
    ]
