# Generated by Django 2.1.8 on 2019-07-26 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FreshApp', '0003_goodstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FreshApp.GoodsType', verbose_name='商品类型'),
            preserve_default=False,
        ),
    ]
